name = "SEMPP"
uuid = "fdfbbab1-c06a-4770-a6f2-a4e776d3db5f"
authors = ["Adam DAVID <adam.david@polytechnique.edu> and contributors"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
